apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:alejandropriv/gitops-infra.git"
    path: environments/development/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
