apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:alejandropriv/gitops-infra.git"
    path: environments/development/trivy-operator
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
